const items = [
  {
    id: 1,
    photo: "../src/img/backpack.webp",
    name: "Backpack",
    price: 45,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },

  {
    id: 2,
    photo: "../src/img/chair.webp",
    name: "Chair",
    price: 350,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 3,
    photo: "../src/img/headphones.webp",
    name: "Headphones",
    price: 149,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 4,
    photo: "../src/img/phone.webp",
    name: "Phone",
    price: 199,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 5,
    photo: "../src/img/shoe.webp",
    name: "Shoe",
    price: 90,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 6,
    photo: "../src/img/tshirt.webp",
    name: "T-shirt",
    price: 15,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 7,
    photo: "../src/img/backpack.png",
    name: "Backpack",
    price: 45,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 8,
    photo: "../src/img/backpack.png",
    name: "Backpack",
    price: 45,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 9,
    photo: "../src/img/backpack.png",
    name: "Backpack",
    price: 45,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
  {
    id: 10,
    photo: "../src/img/backpack.png",
    name: "Backpack",
    price: 45,
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, sed.`,
    category: "Category A",
  },
];

export default items;
